language: android
android:
  components:
    # The BuildTools version used by NewPipe
    - tools
    - build-tools-23.0.2

    # The SDK version used to compile NewPipe
    - android-23

    # Additional components
    - extra-android-support
    - extra-android-m2repository

    # Emulators
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-15

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 by default)
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a